baseURL = 'https://site-fan.github.io/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-US'
defaultContentLanguage = 'en'
theme = 'enchanted-lowkey'
title = 'Site Fan'
enableRobotsTXT = true
summaryLength = 15
paginate = 15


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'dracula'  # Change to your preferred style
    tabWidth = 4

  [markup.goldmark]
    [markup.goldmark.extensions]
      smartypants = true
      definitionList = true
      tables = true
	[markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  math = true

[frontmatter]
  lastmod = [":fileModTime", "lastmod"]
