[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "project"
    name = "Projects"
    url = "/project"
    weight = 6

[[main]]
    identifier = "post"
    name = "Posts"
    url = "/posts"
    weight = 2

# [[main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/categories"
#     weight = 3

[[main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3

[[main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact"
    weight = 4
    
# Social Media Configuration

[[social]]
    identifier = "CV"
    name = "CV"
    url = "/CV_Site_Fan.pdf"
    weight = 1

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:sitefan.official@gmail.com"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/GuTaoZi"
    weight = 3

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/site-fan-322802294/"
    weight = 4

[[social]]
	identifier = "friends"
	name = "Friends!"
	url = "/friends"
	weight = 5
